# Homework SP22 2nd No. 10 - Caroline Eggett


# Refer to chapter 4 (pages 147-177) of Mastering ’Metrics to answer the following questions.
# 1a In order to use a sharp regression discontinuity (RD) design, what must the
# relationship be between the running variable a and the treatment status Da?

# 1b How is a fuzzy RD design different from a sharp RD design?

#2 Consider the following regression model
#   y = α + ρDa+ βa + ε
# where a is the running variable and Dais an indicator function of the form
# Da=
#   {1 if a ≥a0
#    0 if a < a0.

# Generate data from the model above using the following R code.

set.seed(1)
n = 1000
error = rnorm(n)
a = runif(n,0,2)
a0 = 1
Da = ifelse(a>a0,1,0)
y = 1 + 5*Da + 4*a + error

# 2a What is the true value of the treatment effect parameter (ρ) used to generate your
# data?

# 2b Plot y against the running variable a. How does the outcome variable change at
# the cutoff? Include your figure below.

# 2c Use the lm function in R to estimate the parameters (α,β,ρ) from your data.
# What is the estimated treatment effect?

# 2d Load the rdd package in R and estimate the same parameters using the RDestimate
# function command:
#   summary(RDestimate(y ~ a , cutpoint = a0))

# Include the model output below.

# 2e What is the difference in the estimate of ρ in parts (c) and (d)?

# 3 (Demand for Uber1) Understanding the demand for Uber is important not only for
# Uber’s own purposes of setting prices or designing its mobile app, but also for policy
# makers wanting to measure the consequences of ridesharing services on both consumers
# and competitors (e.g., taxis and public transit). Demand models usually take the form of 
# a regression of purchases on price. If prices are exogenously determined, then the coefficient 
# on price represents the causal effect or elasticity of price changes on demand. However, Uber’s 
# prices are not set randomly,but are instead set strategically and in “real-time” to reflect 
# local market conditions. Specifically, Uber’s prices are a function of a base fare, the user’s 
# time in the car, the distance traveled, and a surge price. If, for example, a ride is requested during a
# peak demand time (when the demand for rides exceeds the supply of drivers), Uber
# may charge a surge of 1.5 times the original fare to help move the market towards an
# equilibrium.

# While Uber’s prices are not set randomly, part of the price is random from the consumer’s perspective. 
# It turns out that Uber uses an algorithm to generate surge prices up to an arbitrary number of 
# decimal places, but then shows the consumer a surge price that is rounded to the nearest tenth 
# to ensure an easy user experience. For example, consider two consumers who are requesting a ride 
# in the same city, on the same day, at the same time, from around the same location. Since the 
# local market conditions are nearly identical, Uber’s algorithm would generate nearly identical surges (e.g., 1.2481
# and 1.2513). However, depending on where the generated numbers fall relative to the rounding cutoff, 
# the same two consumers could actually be shown two different surge prices (e.g., 1.2 and 1.3). 
# This allows for the use of regression discontinuity methods to estimate the causal effects of 
# price change on demand and any welfare measure thereafter.
    
# The uber data set reports individual-level session data from n = 1,000,000 users. A session is defined 
# as an instance when a user opens the Uber app, requests a fare, and then decides whether or not to 
# order the ride. The following variables are included: purchase is an indicator for whether a ride was 
# requested or not, generator is the surge price generated by Uber’s algorithm, surge is the surge price 
# actually seen by the consumer, post is an indicator for whether the generated price falls to the right of the
# rounding cutoff, and wait is the expected wait time in minutes.
    
# In reality, Uber’s surge prices can be 1.0,1.2,1.3,...,4.8,4.9,5.0, etc. Going forward,
# however, we will assume that the only surge price offered by Uber is 1.5 times the
# original fare. The set of generated prices then fall in the set (1,1.5), where 1.25 serves
# as the rounding cutoff.

# This question is based on the working paper “Using Big Data to Estimate Consumer Surplus: The Case
# of Uber” which is available at http://www.nber.org/papers/w22627. The data used in this question are
# simulated and roughly based on the results presented in the paper.

# After downloading the data from Carmen, set the path (e.g., "/Users/smith.6588/Downloads")
# and load the data into R using load("path/uber.RData").

# 3a If one was to simply regress purchase on price, which assumption about regression
# models could be violated? How does a regression discontinuity approach help solve
# this problem?

# 3b Use the code below to plot purchase rates against the rounded generator values.
# How does the purchase rate change at the rounding cutoff of 1.25? Include your
# figure below.

gen.round = round(generator,2)
gen.bins = sort(unique(gen.round))
rate.table = as.data.frame.matrix(table(gen.round,purchase))
rates = as.numeric(rate.table[,2]/apply(rate.table,1,sum))
plot(gen.bins,rates,xlab="surge generator",ylab="purchase rate",pch=16,col=2)
abline(v=1.25)

# 3c Use the uber data to estimate the following demand model
# purchase = α + θpost + β1wait + β2generator + ε
# where generator serves as the running variable. Report the model output below.

# 3d Interpret the estimate of θ.

# 3e The analysis in part (c) uses all variation around the cutoff to estimate θ. Create
# a new variable called window that is defined as follows:

#     window =
#       {1 if |generator −1.25|< c
#        0 otherwise
# where c = 0.01. Estimate a second model that includes a window variable to restrict 
# the variation used to be that near the cutoff.

#   purchase = α + θ1(post ∗window) + θ2(post ∗(1 −window))+
#              γwindow + β1wait + β2generator + ε

# Perform a sensitivity analysis with respect to the choice of window. Do the point
# estimates and/or standard errors of θ1 change as window gets larger?

# 3g Convert the estimate of θ from part (e) to a price elasticity as follows:
#   elasticity = %∆ in demand
#   %∆ in price = ˆθ1/purchase rate
#   (1.5 −1)/1
# where purchase rate is the fraction of users who requested a ride when facing a
# surge equal to 1. Do you find the demand for Uber to be elastic or inelastic?

# 3h Based on your reading of the paper, discuss how the following issues would affect
# the authors’ estimated elasticities and subsequent estimates of consumer surplus.

# 3hi Ignoring local competition (e.g., taxis, Lyft, buses, trains).

# 3hii Using price variation during times of high demand to identify causal effects
# of price on demand.